#ifndef CHERRYPROJECTCORE_GLOBAL_H
#define CHERRYPROJECTCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHERRYPROJECTCORE_LIBRARY)
#  define CHERRYPROJECTCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHERRYPROJECTCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHERRYPROJECTCORE_GLOBAL_H
